-- SQL migration + seed for `products` table
-- Run in MySQL Workbench. Review/backup your current table before running.

-- 1) Add new columns to support category, brand, featured flags, bestBefore (expiry) and deal flags.
-- If your MySQL version rejects duplicate ALTERs, run these individually or check INFORMATION_SCHEMA first.
ALTER TABLE products
  ADD COLUMN category VARCHAR(128) DEFAULT 'Uncategorized',
  ADD COLUMN featured TINYINT(1) DEFAULT 0,
  ADD COLUMN brand VARCHAR(128) DEFAULT NULL,
  ADD COLUMN bestBefore DATE DEFAULT NULL,
  ADD COLUMN deal TINYINT(1) DEFAULT 0;

-- 2) Seed product data (100 rows). If you already have some products, consider cleaning duplicates or using INSERT ... ON DUPLICATE KEY UPDATE.
-- The following INSERT assumes your `products` table columns order accepts: (productName, quantity, price, image, category, featured, brand, bestBefore, deal)

INSERT INTO products (productName, quantity, price, image, category, featured, brand, bestBefore, deal) VALUES
('Wholemeal Bread', 40, 2.50, 'bread_wholemeal.jpg', 'Bakery', 0, 'GoldenBake', NULL, 0),
('White Bread', 60, 1.90, 'bread_white.jpg', 'Bakery', 0, 'GoldenBake', NULL, 0),
('Canned Spam', 25, 3.20, 'spam_can.jpg', 'Pantry', 0, 'CanningCo', NULL, 0),
('Instant Noodles (Chicken)', 120, 0.85, 'noodles_chicken.jpg', 'Pantry', 0, 'QuickNoods', NULL, 0),
('Instant Noodles (Beef)', 80, 0.95, 'noodles_beef.jpg', 'Pantry', 0, 'QuickNoods', NULL, 0),
('Eggs (12 pack)', 90, 2.80, 'eggs_12.jpg', 'Dairy', 0, 'SunFarm', NULL, 0),
('Full Cream Milk 1L', 75, 1.60, 'milk_full.jpg', 'Dairy', 0, 'DairyPure', NULL, 0),
('Skim Milk 1L', 50, 1.50, 'milk_skim.jpg', 'Dairy', 0, 'DairyPure', NULL, 0),
('Bananas (kg)', 200, 1.20, 'bananas.jpg', 'Produce', 0, 'HarvestHill', NULL, 0),
('Apples (kg)', 150, 2.20, 'apples.jpg', 'Produce', 0, 'HarvestHill', NULL, 0),
('Baby Spinach', 60, 1.80, 'spinach.jpg', 'Greens', 0, 'GreenLeaf', NULL, 0),
('Romaine Lettuce', 70, 1.40, 'lettuce.jpg', 'Greens', 0, 'GreenLeaf', NULL, 0),
('Frozen Fish Fillet', 45, 6.50, 'fish_fillet.jpg', 'Frozen', 0, 'OceanFresh', NULL, 0),
('Chicken Thighs (1kg)', 50, 5.20, 'chicken_thigh.jpg', 'Poultry', 0, 'SunFarm', NULL, 0),
('Salmon Fillet', 30, 9.50, 'salmon.jpg', 'Fish', 0, 'OceanFresh', NULL, 0),
('Peanut Butter Jar', 80, 3.75, 'peanut_butter.jpg', 'Pantry', 0, 'TasteWell', NULL, 0),
('Tomato Ketchup', 95, 2.00, 'ketchup.jpg', 'Condiments', 0, 'TasteWell', NULL, 0),
('Soya Sauce', 110, 2.30, 'soya_sauce.jpg', 'Condiments', 0, 'TasteWell', NULL, 0),
('Potato Chips', 140, 1.75, 'chips.jpg', 'Snacks', 0, 'Everyday', NULL, 0),
('Instant Oodles (Seafood)', 100, 0.90, 'oodles_seafood.jpg', 'Pantry', 0, 'QuickNoods', NULL, 0),
('Olive Oil 500ml', 55, 6.00, 'olive_oil.jpg', 'Pantry', 0, 'SunFarm', NULL, 0),
('Sparkling Water 1L', 120, 1.20, 'sparkling_water.jpg', 'Beverages', 0, 'Everyday', NULL, 0),
('Coffee (Ground) 250g', 65, 4.85, 'coffee.jpg', 'Pantry', 0, 'TasteWell', NULL, 0),
('Green Tea Bags', 90, 3.10, 'green_tea.jpg', 'Beverages', 0, 'Everyday', NULL, 0),
('Sugar 1kg', 110, 1.90, 'sugar.jpg', 'Pantry', 0, 'Everyday', NULL, 0),
('Butter 250g', 60, 2.40, 'butter.jpg', 'Dairy', 0, 'DairyPure', NULL, 0),
('Cheddar Cheese 200g', 40, 3.80, 'cheddar.jpg', 'Dairy', 0, 'DairyPure', NULL, 0),
('Yogurt (Strawberry) 150g', 85, 1.10, 'yogurt.jpg', 'Dairy', 0, 'DairyPure', NULL, 0),
('Cereal (500g)', 70, 3.50, 'cereal.jpg', 'Pantry', 0, 'HarvestHill', NULL, 0),
('Pasta (Spaghetti) 500g', 95, 1.40, 'pasta.jpg', 'Pantry', 0, 'CanningCo', NULL, 0),
('Tomatoes (kg)', 130, 2.00, 'tomatoes.jpg', 'Produce', 0, 'HarvestHill', NULL, 0),
('Cucumber', 120, 0.90, 'cucumber.jpg', 'Produce', 0, 'GreenLeaf', NULL, 0),
('Carrots (kg)', 140, 1.10, 'carrots.jpg', 'Produce', 0, 'HarvestHill', NULL, 0),
('Onions (kg)', 150, 0.95, 'onions.jpg', 'Produce', 0, 'HarvestHill', NULL, 0),
('Garlic (per bulb)', 200, 0.30, 'garlic.jpg', 'Produce', 0, 'HarvestHill', NULL, 0),
('Canned Tuna', 90, 1.60, 'tuna.jpg', 'Pantry', 0, 'OceanFresh', NULL, 0),
('Mayonnaise 250g', 80, 2.50, 'mayo.jpg', 'Condiments', 0, 'TasteWell', NULL, 0),
('Honey 250g', 45, 4.20, 'honey.jpg', 'Pantry', 0, 'SunFarm', NULL, 0),
('Rice 5kg', 60, 8.50, 'rice.jpg', 'Pantry', 0, 'Everyday', NULL, 0),
('Black Pepper 50g', 70, 2.10, 'pepper.jpg', 'Pantry', 0, 'TasteWell', NULL, 0),
('Salt 1kg', 150, 0.60, 'salt.jpg', 'Pantry', 0, 'Everyday', NULL, 0),
('Canned Beans', 95, 1.30, 'beans.jpg', 'Pantry', 0, 'CanningCo', NULL, 0),
('Chocolate Bar', 180, 1.20, 'chocolate.jpg', 'Snacks', 0, 'Everyday', NULL, 0),
('Ice Cream (Vanilla) 1L', 40, 4.50, 'icecream.jpg', 'Frozen', 0, 'TasteWell', NULL, 0),
('Frozen Pizza', 55, 5.00, 'pizza.jpg', 'Frozen', 0, 'GoldenBake', NULL, 0),
('Sausages 500g', 65, 3.70, 'sausages.jpg', 'Meat', 0, 'SunFarm', NULL, 0),
('Beef Mince 500g', 30, 6.80, 'beef_mince.jpg', 'Meat', 0, 'SunFarm', NULL, 0),
('Toilet Paper 12 pack', 200, 5.90, 'toilet_paper.jpg', 'Household', 0, 'Everyday', NULL, 0),
('Dishwashing Liquid 500ml', 140, 2.20, 'dishwash.jpg', 'Household', 0, 'Everyday', NULL, 0),
('Shampoo 400ml', 120, 4.00, 'shampoo.jpg', 'Household', 0, 'Everyday', NULL, 0),
('Hand Soap', 150, 1.30, 'handsoap.jpg', 'Household', 0, 'Everyday', NULL, 0),
('Fruit Jam 250g', 75, 2.60, 'jam.jpg', 'Pantry', 0, 'TasteWell', NULL, 0),
('Maple Syrup 250ml', 30, 5.50, 'maple.jpg', 'Pantry', 0, 'SunFarm', NULL, 0),
('Almonds 200g', 55, 4.20, 'almonds.jpg', 'Pantry', 0, 'TasteWell', NULL, 0),
('Walnuts 200g', 40, 4.80, 'walnuts.jpg', 'Pantry', 0, 'TasteWell', NULL, 0),
('Orange Juice 1L', 100, 2.20, 'oj.jpg', 'Beverages', 0, 'Everyday', NULL, 0),
('Lentils 500g', 85, 1.90, 'lentils.jpg', 'Pantry', 0, 'CanningCo', NULL, 0),
('Tomato Paste 200g', 95, 0.90, 'tomato_paste.jpg', 'Pantry', 0, 'CanningCo', NULL, 0),
('Pancake Mix 500g', 60, 3.20, 'pancake.jpg', 'Pantry', 0, 'GoldenBake', NULL, 0),
('Sardines (can)', 80, 1.10, 'sardines.jpg', 'Pantry', 0, 'OceanFresh', NULL, 0),
('Mustard 200g', 70, 1.20, 'mustard.jpg', 'Condiments', 0, 'TasteWell', NULL, 0),
('Nutella 350g', 50, 3.90, 'nutella.jpg', 'Pantry', 0, 'TasteWell', NULL, 0),
('Granola 400g', 65, 3.60, 'granola.jpg', 'Pantry', 0, 'HarvestHill', NULL, 0),
('Cottage Cheese 200g', 45, 2.50, 'cottage.jpg', 'Dairy', 0, 'DairyPure', NULL, 0),
('Frozen Vegetables 500g', 90, 2.30, 'frozen_veg.jpg', 'Frozen', 0, 'GreenLeaf', NULL, 0),
('Bagels (6 pack)', 40, 2.70, 'bagels.jpg', 'Bakery', 0, 'GoldenBake', NULL, 0),
('Croissant (single)', 120, 0.95, 'croissant.jpg', 'Bakery', 0, 'GoldenBake', NULL, 0),
('Muesli Bars (6)', 130, 2.50, 'muesli.jpg', 'Snacks', 0, 'HarvestHill', NULL, 0),
('Tortilla Wraps', 75, 2.10, 'tortilla.jpg', 'Pantry', 0, 'CanningCo', NULL, 0),
('Mayonnaise Light', 80, 2.30, 'mayo_light.jpg', 'Condiments', 0, 'TasteWell', NULL, 0),
('BBQ Sauce', 90, 2.20, 'bbq.jpg', 'Condiments', 0, 'TasteWell', NULL, 0),
('Energy Drink 330ml', 140, 1.80, 'energy.jpg', 'Beverages', 0, 'Everyday', NULL, 0),
('Protein Powder 1kg', 25, 22.50, 'protein.jpg', 'Pantry', 0, 'TasteWell', NULL, 0),
('Canned Corn', 110, 1.00, 'corn.jpg', 'Pantry', 0, 'CanningCo', NULL, 0),
('Baby Food (Jar)', 65, 1.50, 'babyfood.jpg', 'Pantry', 0, 'SunFarm', NULL, 0),
('Dog Food 2kg', 60, 5.80, 'dogfood.jpg', 'Household', 0, 'Everyday', NULL, 0),
('Cat Food 1kg', 70, 4.10, 'catfood.jpg', 'Household', 0, 'Everyday', NULL, 0),
('Toothpaste 100ml', 120, 1.90, 'toothpaste.jpg', 'Household', 0, 'Everyday', NULL, 0),
('Shaving Foam', 80, 2.10, 'shave.jpg', 'Household', 0, 'Everyday', NULL, 0),
('Face Wash', 75, 3.50, 'facewash.jpg', 'Household', 0, 'Everyday', NULL, 0),
('Lip Balm', 150, 1.20, 'lipbalm.jpg', 'Household', 0, 'Everyday', NULL, 0),
('Sushi Rice 1kg', 50, 6.00, 'sushi_rice.jpg', 'Pantry', 0, 'Everyday', NULL, 0),
('Wasabi Paste 50g', 40, 1.50, 'wasabi.jpg', 'Condiments', 0, 'TasteWell', NULL, 0),
('Seaweed Snacks', 80, 1.10, 'seaweed.jpg', 'Snacks', 0, 'OceanFresh', NULL, 0),
('Rice Crackers', 90, 1.40, 'crackers.jpg', 'Snacks', 0, 'Everyday', NULL, 0),
('Maple Granola', 60, 4.20, 'maple_granola.jpg', 'Pantry', 1, 'HarvestHill', '2025-12-05', 1),
('Expiring Yogurt 150g', 10, 0.60, 'yogurt_exp.jpg', 'Dairy', 1, 'DairyPure', '2025-11-25', 1),
('Discount Salmon Fillet', 5, 6.50, 'salmon_discount.jpg', 'Fish', 1, 'OceanFresh', '2025-11-26', 1),
('Short-dated Bread', 4, 0.80, 'bread_short.jpg', 'Bakery', 1, 'GoldenBake', '2025-11-24', 1),
('Seasonal Fruit Pack', 20, 4.00, 'seasonal_fruit.jpg', 'Produce', 1, 'HarvestHill', '2025-12-01', 1);

-- End of migration + seed
